language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows

script:
  - ci/ci.sh
  - ci/release.sh

env:
  matrix:
    secure: C7SxNrJPLvrmH3F6ypSjwnbJBObM5gO1bQKJ+DtdWip+UhqNwhNc4zM8OO7fTvzBC7y7ppMj7X8v7fcFbn++XFWwdmaVb6F9dmaSRHPMT9zZ05p9ypmWhJzoz4/Z+01kU8VCapj7Gl9GK/T1rbQv18Lf6r5Ke6BKnXP6ji2LmtajQ35a+Nsw9lrFlChv/vQ4lVwbkXqu64Uq4RGDy8XtHPAm+SAIyFQA0Op2gpPDv8HZn/EtvyWszlhecVUvh8WK39YH0wb5rSp6xIOrwBJWp99bYzXlPnAA14vcljQ0/Kb/rlM0iLnrLwDfGBfY/uTdC7XVQpQSd4qPNBTVTTU2XnTX+pSKpniIDhKPPlNvIPD9jdngUHRIcut9KObxpyd3vOJEAgO/rNb3smK0M6ubYndV2dYHpUimpxOQU+EAflXqvvtmPbJBRkdr3LtoOYVPpjXl2/HHR1bqLILeHoW0ZnGy3YflziRnTtaam3uirh7Un39yhWZ+IgFD6EswUAyLt1x0aDR5fCmUc82PdRvkgKbmzQO3V7GnCbDl6FBHYoEqfwFp/gVzEEFn82xJN1VEFxzHAaa6Q6yXB90l6iA/QYz5d1fZ8ZL2kBfHN8ywzK4vVfIYfoLRtHkYRQa+wJL+VV+ci/8pahX+eg4gzFwAncQYdrawx/jdMjPWtR7Asmk=
